version: '3.8'

services:
  app:
    container_name: mebeltut_app
    build:
      context: .
    env_file:
      - .env
    command: bash -c "
      export ENVIROMENT='local' &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - mebeltut-network
    volumes:
      - ./src:/src

  database:
    container_name: mebeltut_base
    image: postgres:14.5
    command: postgres -c 'max_connections=1000'
    expose:
      - 5444
    ports:
      - "5444:5432"
    restart: always
    env_file:
      - .env
    networks:
      - mebeltut-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mebeltut-network:
    driver: bridge

volumes:
  postgres_data:
