# Generated by Django 5.1.3 on 2024-12-02 09:57

import apps.main.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Мебель тут", max_length=50, verbose_name="Название"
                    ),
                ),
                ("street", models.CharField(max_length=20, verbose_name="Улица")),
                ("number", models.IntegerField(verbose_name="Дом")),
                ("building", models.CharField(max_length=5, verbose_name="Корпус")),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Категория")),
                (
                    "slug",
                    models.SlugField(default="", unique=True, verbose_name="Ссылка"),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True, unique=True, verbose_name="Номер в списке"
                    ),
                ),
                (
                    "isCabinet",
                    models.BooleanField(
                        default=False, verbose_name="Корпусная мебель?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Коллекция")),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.main.models.collection_directory_path,
                        verbose_name="Фото категории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(default="", unique=True, verbose_name="Ссылка"),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="CategoryInCollection",
                        to="main.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Номер")),
                ("isViber", models.BooleanField(verbose_name="Viber")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.address",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телефон",
                "verbose_name_plural": "Телефоны",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("isOnSale", models.BooleanField(verbose_name="Акция")),
                (
                    "rating",
                    models.IntegerField(
                        default=758,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "mainImage",
                    models.ImageField(
                        upload_to=apps.main.models.product_directory_path,
                        verbose_name="Главное фото",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(default="", unique=True, verbose_name="Ссылка"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="main.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.collection",
                        verbose_name="Коллекция",
                    ),
                ),
                (
                    "collectionCategory",
                    models.ManyToManyField(
                        blank=True,
                        related_name="category2collection",
                        to="main.category",
                        verbose_name="Категория для коллекции",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Номер")),
                (
                    "product_name",
                    models.CharField(
                        default="Товар", max_length=30, verbose_name="Название товара"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата добавления",
                    ),
                ),
                ("link", models.URLField(default="http://127.0.0.1:8000/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.main.models.image_directory_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.CreateModel(
            name="Specs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param",
                    models.CharField(
                        choices=[
                            ("Length", "Длина"),
                            ("Width", "Ширина"),
                            ("Height", "Высота"),
                            ("Weight", "Вес"),
                            ("Bed length", "Длина спального места"),
                            ("Bed width", "Ширина спального места"),
                            ("Transformation mechanism", "Механизм трансформации"),
                            (
                                "The presence of drawers for linen",
                                "Наличие ящиков для белья",
                            ),
                            ("Corner", "Угол"),
                            ("Material", "Материал"),
                            ("Color", "Цвет"),
                            ("Maximum load", "Максимальная нагрузка"),
                            ("Tabletop thickness", "Толщина столешницы"),
                            ("Additional Information", "Дополнительная информация"),
                        ],
                        max_length=100,
                        verbose_name="Параметр",
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mm", "мм"),
                            ("sm", "см"),
                            ("pc", "шт"),
                            ("kg", "кг"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Ед. измерения",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
    ]
