# Generated by Django 4.1.7 on 2023-03-25 15:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_date_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 15, 24, 59, 218980, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=432, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='param',
            field=models.CharField(choices=[('Length', 'Длинна'), ('Width', 'Ширина'), ('Height', 'Высота'), ('Weight', 'Вес'), ('Bed length', 'Длина спального места'), ('Bed width', 'Ширина спального места'), ('Transformation mechanism', 'Механизм трансформации'), ('The presence of drawers for linen', 'Наличие ящиков для белья'), ('Corner', 'Угол'), ('Material', 'Материал'), ('Color', 'Цвет'), ('Maximum load', 'Максимальная нагрузка'), ('Tabletop thickness', 'Толщина столешницы'), ('Additional Information', 'Дополнительная информация')], max_length=100, unique=True, verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='specs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар'),
        ),
    ]
