# Generated by Django 4.1.7 on 2023-03-25 15:56
import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_product_collection_alter_product_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 25, 15, 56, 29, 236028, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=604,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="specs",
            name="param",
            field=models.CharField(
                choices=[
                    ("Length", "Длинна"),
                    ("Width", "Ширина"),
                    ("Height", "Высота"),
                    ("Weight", "Вес"),
                    ("Bed length", "Длина спального места"),
                    ("Bed width", "Ширина спального места"),
                    ("Transformation mechanism", "Механизм трансформации"),
                    ("The presence of drawers for linen", "Наличие ящиков для белья"),
                    ("Corner", "Угол"),
                    ("Material", "Материал"),
                    ("Color", "Цвет"),
                    ("Maximum load", "Максимальная нагрузка"),
                    ("Tabletop thickness", "Толщина столешницы"),
                    ("Additional Information", "Дополнительная информация"),
                ],
                max_length=100,
                verbose_name="Параметр",
            ),
        ),
    ]
