# Generated by Django 4.1.7 on 2023-03-26 11:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_phone_alter_manufacturer_name_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='isViber',
            field=models.BooleanField(default=True, unique=True, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='phone',
            name='store',
            field=models.CharField(default='Брестская', max_length=20, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 11, 35, 16, 996885, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=122, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
    ]
