# Generated by Django 4.1.7 on 2023-03-27 10:12
import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_phone_isviber_phone_store_alter_product_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="isCabinet",
            field=models.BooleanField(default=False, verbose_name="Корпусная мебель?"),
        ),
        migrations.AddField(
            model_name="category",
            name="number",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="Номер в списке"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="isViber",
            field=models.BooleanField(unique=True, verbose_name="Viber"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="store",
            field=models.CharField(max_length=20, verbose_name="Магазин"),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 27, 10, 12, 44, 324678, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=814,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="specs",
            name="param",
            field=models.CharField(
                choices=[
                    ("Length", "Длина"),
                    ("Width", "Ширина"),
                    ("Height", "Высота"),
                    ("Weight", "Вес"),
                    ("Bed length", "Длина спального места"),
                    ("Bed width", "Ширина спального места"),
                    ("Transformation mechanism", "Механизм трансформации"),
                    ("The presence of drawers for linen", "Наличие ящиков для белья"),
                    ("Corner", "Угол"),
                    ("Material", "Материал"),
                    ("Color", "Цвет"),
                    ("Maximum load", "Максимальная нагрузка"),
                    ("Tabletop thickness", "Толщина столешницы"),
                    ("Additional Information", "Дополнительная информация"),
                ],
                max_length=100,
                verbose_name="Параметр",
            ),
        ),
    ]
