# Generated by Django 4.1.7 on 2023-03-28 11:25
import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_category_iscabinet_category_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 28, 11, 25, 58, 222171, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=672,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
