# Generated by Django 4.1.7 on 2023-03-29 07:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_price_alter_product_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 7, 35, 0, 282755, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=217, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='collection',
            name='manufacturer',
            field=models.ManyToManyField(to='main.manufacturer', verbose_name='Производитель'),
        ),
    ]
