# Generated by Django 4.1.7 on 2023-03-31 15:52
import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_phone_store_alter_product_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="isViber",
            field=models.BooleanField(verbose_name="Viber"),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 31, 15, 52, 16, 728656, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=530,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
