# Generated by Django 4.1.7 on 2023-04-19 08:43
import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_phone_isviber_alter_product_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone",
            name="isMain",
        ),
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(
                default="Мебель тут", max_length=50, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 19, 8, 43, 31, 567875, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=7, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
