# Generated by Django 4.1.7 on 2023-04-29 13:55
import datetime

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_alter_feedback_date_alter_product_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="product_link",
            new_name="product",
        ),
        migrations.AddField(
            model_name="feedback",
            name="link",
            field=models.URLField(default="http://127.0.0.1:8000/"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 13, 55, 12, 338256, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 13, 55, 12, 334763, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=206,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
