# Generated by Django 3.2.19 on 2023-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20230511_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='param',
            field=models.CharField(choices=[('Length', 'Длина'), ('Width', 'Ширина'), ('Height', 'Высота'), ('Weight', 'Вес'), ('Bed length', 'Длина спального места'), ('Bed width', 'Ширина спального места'), ('Transformation mechanism', 'Механизм трансформации'), ('The presence of drawers for linen', 'Наличие ящиков для белья'), ('Corner', 'Угол'), ('Material', 'Материал'), ('Color', 'Цвет'), ('Maximum load', 'Максимальная нагрузка'), ('Tabletop thickness', 'Толщина столешницы'), ('Additional Information', 'Дополнительная информация'), ('Link', 'Ссылка')], max_length=100, verbose_name='Параметр'),
        ),
    ]
