# Generated by Django 3.2.19 on 2023-05-13 18:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_alter_specs_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specs",
            name="value",
            field=models.CharField(max_length=400, verbose_name="Значение"),
        ),
    ]
