# Generated by Django 3.2.19 on 2023-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_specs_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specs',
            name='value',
            field=models.CharField(max_length=800, verbose_name='Значение'),
        ),
    ]
