# Generated by Django 3.2.19 on 2023-05-13 18:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_alter_specs_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specs",
            name="value",
            field=models.CharField(max_length=255, verbose_name="Значение"),
        ),
    ]
