# Generated by Django 4.1.7 on 2023-03-25 13:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Категория")),
                ("slug", models.SlugField(default="", unique=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Коллекция")),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.collection_directory_path,
                        verbose_name="Фото категории",
                    ),
                ),
                ("slug", models.SlugField(default="", unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
                ("isOnSale", models.BooleanField(verbose_name="Акция")),
                (
                    "rating",
                    models.IntegerField(
                        default=821,
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "mainImage",
                    models.ImageField(
                        upload_to=main.models.product_directory_path,
                        verbose_name="Главное фото",
                    ),
                ),
                ("slug", models.SlugField(default="", unique=True)),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            3,
                            25,
                            13,
                            43,
                            28,
                            121035,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Specs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "param",
                    models.CharField(
                        choices=[
                            ("Length", "Длинна"),
                            ("Width", "Ширина"),
                            ("Height", "Высота"),
                            ("Bed length", "Длина спального места"),
                            ("Bed width", "Ширина спального места"),
                            ("Transformation mechanism", "Механизм трансформации"),
                            (
                                "The presence of drawers for linen",
                                "Наличие ящиков для белья",
                            ),
                            ("Corner", "Угол"),
                            ("Material", "Материал"),
                            ("Color", "Цвет"),
                            ("Maximum load", "Максимальная нагрузка"),
                            ("Tabletop thickness", "Толщина столешницы"),
                            ("Additional Information", "Дополнительная информация"),
                        ],
                        max_length=100,
                        verbose_name="Параметр",
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Ед. измерения",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристики",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=main.models.product_directory_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
    ]
