# Generated by Django 4.1.7 on 2023-04-22 16:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_feedback_alter_product_date_alter_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="product_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 22, 16, 20, 30, 513161, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=766,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
