# Generated by Django 4.1.7 on 2023-04-27 14:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_feedback_product_link_alter_product_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="collectionCategory",
            field=models.ManyToManyField(
                blank=True,
                related_name="category2collection",
                to="main.category",
                verbose_name="Категория для коллекции",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 27, 14, 12, 50, 335173, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=910,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
