# Generated by Django 4.1.7 on 2023-04-29 09:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_alter_product_date_alter_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 9, 38, 51, 696540, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 9, 38, 51, 693279, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=890,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
