# Generated by Django 4.1.7 on 2023-04-29 16:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_rename_product_link_feedback_product_feedback_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="product_name",
            field=models.CharField(
                default="Товар", max_length=30, verbose_name="Название товара"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 16, 12, 31, 420026, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 29, 16, 12, 31, 415542, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата добавления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=710,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
