# Generated by Django 4.1.7 on 2023-05-01 08:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_alter_feedback_date_alter_product_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата добавления"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                default=732,
                validators=[
                    django.core.validators.MaxValueValidator(1000),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
