# Generated by Django 5.1.3 on 2024-12-04 16:19
import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0009_alter_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "customer_first_name",
                    models.CharField(max_length=255, verbose_name="Имя"),
                ),
                (
                    "customer_last_name",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "customer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="BY",
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Наличные"),
                            ("Card", "Картой"),
                            ("Installment_plan", "Рассрочка"),
                            ("Credit", "Кредит"),
                        ],
                        max_length=255,
                        verbose_name="Метод оплаты",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("Delivery", "Доставка"), ("Pickup", "Самовывоз")],
                        max_length=255,
                        verbose_name="Метод доставки",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "Новый"),
                            ("In progress", "В процессе"),
                            ("Completed", "Завершён"),
                            ("Cancelled", "Отменён"),
                        ],
                        default="New",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "pickup_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.address",
                        verbose_name="Адрес самовывоза",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
        ),
    ]
