# Generated by Django 5.1.3 on 2024-12-04 16:41
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BY", verbose_name="Номер телефона"
            ),
        ),
    ]
