# Generated by Django 5.1.3 on 2024-12-06 19:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_cart_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Позиция", "verbose_name_plural": "Позиции"},
        ),
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
