# Generated by Django 5.1.3 on 2024-12-08 20:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_options_order_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "Новый"),
                            ("In progress", "В процессе"),
                            ("Completed", "Завершён"),
                            ("Cancelled", "Отменён"),
                        ],
                        default="New",
                        max_length=20,
                        verbose_name="Статус доставки",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "courier",
                    models.CharField(max_length=255, verbose_name="Имя курьера"),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Позиция в корзине",
                "verbose_name_plural": "Позиции в корзине",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="orders.delivery",
            ),
        ),
    ]
