# Generated by Django 5.1.3 on 2024-12-09 16:51
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_product_rating"),
        ("orders", "0004_delivery_alter_cartitem_options_order_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="shop_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.address",
                verbose_name="Магазин",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата"),
        ),
    ]
