# Generated by Django 5.1.3 on 2024-12-09 17:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_delivery_shop_address_alter_delivery_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="total_distance",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Расстояние (км)"
            ),
        ),
    ]
